# Test configuration file recreating development defaults

model_save_file: /home/lverhoef/glp/glp_ri/saved_models/crps_cnn.pt

training_hyperparameters:
  batches_per_epoch: 64
  batch_size: 64
  epochs: 1000
  accumulation_batches: 2
  loss_function: crps
  learning_rate: 1.0e-3
  early_stopping:
    enabled: True
    patience: 20
    min_delta: 1.0e-4

data_augmentation:
  rotations:
    max_degrees: 50
    num_rotations: 2
  noisings:
    standard_deviation: 0.5
    num_noisings: 2
  translations:
    max_shift: 0.05
    num_translations: 3

encoding_layers:
  conv_block_1:
    type: conv_block
    in_channels: 1
    out_channels: 8
  conv_block_2:
    type: conv_block
    in_channels: 8
    out_channels: 16
  conv_block_3:
    type: conv_block
    in_channels: 16
    out_channels: 32
  conv_block_4:
    type: conv_block
    in_channels: 32
    out_channels: 64
  conv_block_5:
    type: conv_block
    in_channels: 64
    out_channels: 128
  conv_block_6:
    type: conv_block
    in_channels: 128
    out_channels: 256

encoding_layer_defaults:
  leaky_relu_slope: 0.2

dense_layers:
  dense_block_1:
    type: dense_block
    in_neurons: 10240
    out_neurons: 1740
  dense_block_2:
    type: dense_block
    in_neurons: 1740
    out_neurons: 1305
  dense_block_3:
    type: dense_block
    in_neurons: 1305
    out_neurons: 870
  dense_block_4:
    type: dense_block
    in_neurons: 870
    out_neurons: 435

dense_layer_defaults:
  dropout_rate: 0.2
  leaky_relu_slope: 0.2

output_layer:
  out_layer:
    type: linear
    in_features: 435
    out_features: 100
