# Test configuration file recreating development defaults

encoding_layers:
  conv_block_1:
    type: conv_block
    in_channels: 1
    out_channels: 8
  conv_block_2:
    type: conv_block
    in_channels: 8
    out_channels: 16
  conv_block_3:
    type: conv_block
    in_channels: 16
    out_channels: 32
  conv_block_4:
    type: conv_block
    in_channels: 32
    out_channels: 64
  conv_block_5:
    type: conv_block
    in_channels: 64
    out_channels: 128
  conv_block_6:
    type: conv_block
    in_channels: 128
    out_channels: 256

encoding_layer_defaults:
  leaky_relu_slope: 0.2

dense_layers:
  dense_block_1:
    type: dense_block
    in_neurons: 10240
    out_neurons: 1740
  dense_block_2:
    type: dense_block
    in_neurons: 1740
    out_neurons: 1305
  dense_block_3:
    type: dense_block
    in_neurons: 1305
    out_neurons: 870
  dense_block_4:
    type: dense_block
    in_neurons: 870
    out_neurons: 435

dense_layer_defaults:
  dropout_rate: 0.2
  leaky_relu_slope: 0.2

output_layer:
  out_layer:
    type: linear
    in_features: 435
    out_features: 100

training_hyperparameters:
  loss_function: crps
  learning_rate: 1e-3
  early_stopping:
    enabled: True
    patience: 20
    min_delta: 1e-4
